- aliases:
    - &ESOMAIN eso_main
    - &CONTAINER_ESO eso
    - &MAIN main
    - &DEFAULT_NS main
    - &STRAP strap
    - &TC telco
    - &TOGGLE toggle
    - &PLAY play
    - &PAUSE pause
    - &STORY story
    - &PROTO proto
    - &LAYER layer
    - &BLOC bloc
    - &IMG img
    - &SPRITE sprite
    - &BUTTON button
